from time import sleep

while True:
    pass
    print("rr")

print ("\nThis programe can't be run in DOS mode\n")
sleep(2)

print ("Donnerstag, den 19.Oktober\n")
sleep(2)
print ("correction de l'évaluation:\n\n")
sleep(2)
print ("ex 1:\n\n")
sleep(2)
print ("2 Wir sind.\n")
sleep(2)
print ("3 sie hat.\n")
sleep(2)
print ("4 habe.\n")
sleep(2)
print ("5 ihr seid.\n")
sleep(2)
print ("6 du hast.\n")
sleep(2)
print ("7 haben.\n")
sleep(2)
print ("8 ihr habt.\n")
sleep(2)
print ("9 Sie sind.\n")
sleep(2)
print ("10 Ich bin Krank.\n")
sleep(2)
print ("11 du bist gekommen.\n")
sleep(2)
print ("12 er ist nicht da.\n")
sleep(2)
print ("13 Die Katze ist eingeschlafen einschlafen=s'endormir.\n")
sleep(2)
print ("14 ihr habt eine lange reise gemacht.\n")
sleep(2)
print ("15 Die kinder sind aufgewart.\n")
sleep(2)
print ("ex 2:\n\n")
sleep(2)
print ("1 Um sieben uhr morgens stehe ich sieben uhr auf.\n")
sleep(2)
print ("  Ich stehe um sieben uhr morgens auf.\n")
sleep(2)
print ("  Um sieben uhr ich morgens auf.\n")
sleep(2)
print ("  Ich stehe morgens um sieben uhr auf.\n\n")
sleep(2)
print ("2 Eine Freundin-an-sie-ruft.\n")
sleep(2)
print ("  Sie ruft eine Freundin an.\n")
sleep(2)
print ("  Eine Freundin ruft sie an.\n\n")
sleep(2)
print ("3 Nach-meine-Schule-an-ziehen-dem-Früstück-an.\n")
sleep(2)
print ("  Nach dem Früstüch ziehen ich meine Schuhe an.\n")
sleep(2)
print ("  Ich ziehe meine Schuhe nach dem Früstück an.\n\n")
sleep(2)
print ("4 Ein-Im-Supermarkt-kauft-sie-an.\n")
sleep(2)
print ("  Sie kauft im Supermerkt ein.\n")
sleep(2)
print ("  Im Supermarkt kauft sie ein.\n\n")
sleep(2)
print ("5 Am-Abend-sie-fern-sehen\n")
sleep(2)
print ("  Am Abend sehen sie fern.\n")
sleep(2)
print ("  Sie sehen am Abend fern.\n\n")
sleep(2)
print ("6 Geburstag-17-am-Februar-habe-ich.\n")
sleep(2)
print ("  Ich habe Geburstag am 17. Februar.\n")
sleep(2)
print ("  Am 17. Februar habe ich geburstag.\n\n")
sleep(2)
print ("ex 3\n\n")
sleep(2)
print ("1) Le frigo est plein.\n")
sleep(2)
print ("2) ça me plaît.\n")
sleep(2)
print ("3) Je me sent bien dans ma chambre.\n")
sleep(2)
print ("4) J'aime bien toutes les saisons.\n")
sleep(2)
print ("5) Je vis avec ma mère et mon frère\n")
sleep(2)
print ("6) Je suis la majorité du temps dans le salon.\n")
sleep(2)
print ("7) Je suis très souvent à la maison.\n")
sleep(2)
print ("8) Je passe du temps avec mes amis.\n")
sleep(2)
print("Die entscheidung=la décision\n")
sleep(2)
print ("sich entscheiden=se décider\n")
sleep(2)
print ("Traduction de l'e-mail en Allemand.\n")
sleep(2)
print ("Teilnehemen = Participer.\n")
sleep(2)
print ("Ich nehme am Programm Voltaire teil.\n")
sleep(2)
print ("die Teilnahme: la participation.\n")
print ("teilnehmen: participer")
sleep(2)
print ("die Entscheidng: la décision.\n")
sleep(2)
print ("Sich entscheiden: se décider.\n")
sleep(2)
print ("empfehlen: conseiller\n")
sleep(2)
print ("Die Empfehlung: la recommandation\n")
sleep(2)
print("Die Möglichkeit: la possibilité\n")
sleep(2)
print ("ein/tauschen:échanger\n")
sleep(2)
print ("Das dorf: le village\n")
sleep(2)
print ("Die Stadt: la ville\n")
sleep(2)
print ("gross: grand\n")
sleep(2)
print ("Die Grosstadt: la grande ville.\n")
sleep(2)
print ("jeden/jeder: à chacun\n")
sleep(2)
print ("der Schritt: le pas\n")
sleep(2)
print ("Ich habe gelernt\n")
sleep(2)
print ("lernen: apprendre\n")
sleep(2)
print ("die Erfahrung: l'expérience\n")
sleep(2)
print ("sammeln: collectionner/collecter\n")
sleep(2)
print ("gewinnen: gagner\n")
sleep(2)
print ("Ich habe Freunde gewonnen: j'ai ganer des amis\n")
sleep(2)
print ("wohnen: habiter: \n")
sleep(2)
print ("gewonnen:\n")
sleep(2)
print ("Die Umfrage: le sondage\n")
sleep(2)
print ("teilen: échanger/ partager\n")
sleep(2)
print ("gleich/selb: les mêmes\n")
sleep(2)
print ("unterstützen=protéger\n")
sleep(2)
print ("Dick: gros\n")
sleep(2)
print("Lieb gewinnen: gagner leur amour\n")
sleep(2)
print("mit jemanden klarkommen: s'entendre avec(qq)\n")
sleep(2)
print ("nähr bringen: rendre + accessible\n")
sleep(2)
print ("sich zu hause fühlen: se sentir chez soi\n")
sleep(2)
